### ISSUE TITLE
http://martin-loetzsch.de/ht-simple-ajax/ yields 403 access forbidden

### ISSUE THREAD

**Issue by digikar99** [martin-loetzsch/ht-simple-ajax#1]
Hi! The linked website <http://martin-loetzsch.de/ht-simple-ajax/> yields a 403 access forbidden error. 7 years later, you can prolly host the site on github pages by removing line 1 `<?xml ...>` from `index.html`!

**Comment by martin-loetzsch** [comment]
It's back, thanks for notifying

I'm really surprised this is still used :)
